version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NUM_TASKS=${NUM_TASKS}
      - TASK_DELAY=${TASK_DELAY}
    networks:
      - task-network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge